/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as passportSbtSol from "./PassportSBT.sol";
export type { passportSbtSol };
export type { AttestationRegistry } from "./AttestationRegistry";
export type { DisputeResolutionDAO } from "./DisputeResolutionDAO";
export type { EndorsementRegistry } from "./EndorsementRegistry";
export type { PassportFacade } from "./PassportFacade";
export type { ReputationOracle } from "./ReputationOracle";
