/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC5192__factory } from "./IERC5192__factory";
export { PassportSBT__factory } from "./PassportSBT__factory";
